# TCP cho notification-service (Node.js)
listener 1883
protocol mqtt

# WebSocket cho test-client trên trình duyệt
listener 9001
protocol websockets

# Dev only — production phải tắt
allow_anonymous true